[package]
name = "guess_word"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
text_io = "0.1.9"
rand = "0.8.4"
tui = "0.17.0"
crossterm = "0.22"
unicode-width = "0.1"
